### ISSUE TITLE
Capacitor 3

### ISSUE THREAD

**Issue by danielehrhardt** [aparajita/ws-capacitor-native-decorator#1]
Could you update the Plugin to make it work with Capacitor 3?

**Comment by aparajita** [comment]
Hi @danielehrhardt, the upgrade is done, and I added support for callbacks as well. I'm verifying it with my other plugins, then it will be published to @capacitor-community. Soon!

**Comment by aparajita** [comment]
@danielehrhardt Just published v2.0.0 to @aparajita/capacitor-native-decorator. Let me know if you have any issues.
